-- Dummy Data for Medium Clone
-- DevMountain Personal Project

--TAGS: 
--HTML, CSS, JavaScript, Angular, React, food, politics, health, environment, science, tech, space, future, health, celebrities, music, art, humor

--REMOVE id TAG AND FIRST VALUE OF EVERY INSERTION


INSERT INTO articles
(author_id, title, body, date_published, published, tags, views, likes, bookmarks, responses, response_parent)
VALUES
(1, 1, 'Donald Trump is Unimpeachable. Here’s Why.', '<p>There is no question that Donald J. Trump is a lying, thieving, backstabbing, two-faced, violent criminal.</p>
<p>There is also no doubt that he is the front man for a far-right network of white nationalist politicians and businessmen that want to revive the Confederacy. This network has been contracted by Vladimir Putin to facilitate the takeover of the federal government of the United States as part of a larger effort to dismantle western nations, alliances and power. Collectively, they have occupied the White House and begun the process of dismantling the federal government, isolating the US from its allies, bankrupting the economy, restructuring and hyper-funding the military and cleansing the nation of people of color, the poor, people living with disabilities, non-Christians, and anyone else not deemed part of the master race. Together, under the authority of Donald Trump and his Republican Congress, the GOP and the Russian government are gutting the corpse of the United States and positioning its zombie carcass to carry out the will of an adversarial Putin led eastern alliance that is openly working to dismantle the Western World.
</p><p>And he is legally unimpeachable.</p>I<p>n the United States, the only entity that can impeach Donald Trump is Congress. A Congress that has formed a united front against the Democrats, against Civil Rights, against the people of the United States and in support of Vladimir Putin. They do not respond to their constituencies, their duties as officials, the constitution, media pressure or public shaming. They respond to their contracts. Which have been implemented with the explicit intent to prevent the removal of Putin’s GOP puppet government.
<p>Congress will not impeach Trump.</p>
<p>Here’s why. The Constitution gives only the House of Representatives the legal authority to bring formal charges of impeachment against a sitting president. It would take half of Congress to successfully bring charges. The Senate has sole power to bring a president to trial for impeachment. Two-thirds of the Senate would have to vote to convict and remove Trump from office to successfully impeach him. With the GOP in control of both the House and the Senate, as planned, there is no chance that the GOP will violate its contract with the Russian government in order to impeach Trump.
</p><p>So here’s the quick takeaway:</p>
<p>The United States has been taken over by a white nationalist puppet government contracted by the Russian government. They want to dismantle federal authority in the United States and all western nations for their own political, economic, social and military visions of an ethnically-cleansed, post western world order.
They are willing to lie, cheat, break laws, and murder to accomplish their goals. They know how to rig elections and utilize mafia tactics. They don’t respond to constituencies, political pressure, or the media. They cannot be shamed away, tweeted away, marched away or phone called away. The will not be investigated by the GOP controlled House and Senate Oversight Committees or Department of Justice. They cannot be impeached.
</p><p>Ok, that’s a lot. It might be more than you want to hear. But it’s what’s happening. Take it in. Take a breath.
</p><p>Let’s continue.</p>
<p>This isn’t going to be easy to digest.</p>The formal plan to overthrow the federal government of the United States has been in action for years. Vladimir Putin is a ruthless military and political strategist. He knows the offensive and defensive histories, strengths and weaknesses of his nation, its alliances, it’s adversaries and those standing in the way of his ultimate goals. And his ultimate goals don’t begin and end with Hillary Clinton or even the United States. Vladimir Putin is years into a strategy designed to take over the federal governments of the Western powers, install puppet regimes, dismantle their individual and collective authority and usher in a Russian led new world order.</p>
<p>Putin didn’t just up and one day decide that he was going to partner with a C level businessman and celebrity to embarrass Hillary Clinton. He has been plotting to tear down the western alliance — including the UN and NATO — since his days in the KGB and has spent years successfully guiding the GOP to victory in their efforts to take Congress and the White House.</p>
<p>Putin considered every lever necessary to pull to ensure his puppet government would take the White House and that there would not be anything that could be done by Congress or the federal government to unseat him. He planned, he executed and he won. He didn’t just win, but Putin and the White Nationalist network he contracted to carry out his agenda kicked our assess. And they are still in power — kicking our asses.</p>
<p>What’s worse, the Democrats had numerous opportunities to counter the maneuvers of the GOP and they did nothing. As the stated defenders of minority rights and the strategic defenders of the nation against the Conservative Confederacy, they failed to live up to their responsibilities. This failure allowed them to be easily defeated by the GOP’s efforts to dismantle federal authority and Putin’s efforts to dismantle the West.</p>
<p>Every nation has specific governmental, political, and social systems that must be considered when designing a strategic agenda. Different strategies were required for the UK than in the United States. Different levers needed to be pulled to accomplish Brexit than to pull off MAGA.</p>
<p>In the United States, Putin needed to identify a far-right conservative network that aligned with his vision to dismantle federal authority and implement a system of white nationalism. He did not have to look hard to find the GOP and its neo-Confederate heart. That core has functioned since the Civil War and its Confederate flags still fly high around the United States. It has used force, laws and criminal activity to dismantle civil rights, suppress voting, incarcerate and impoverish communities not of the chosen race, and take land from sovereign entities.</p>
<p>The overwhelming majority of GOP candidates and members of the Trump administration are funded by Robert Mercer, David & Charles Koch, Sheldon Adelson, the Scaife family, the DeVos family and other core members of the far-right funding megalith, the Donor’s Trust. These individuals are responsible for such entities as the Tea Party, Freedomworks, the Heritage Foundation, the American Enterprise Institute, the Manhattan Institute and the Federation of American Immigration Reform. They are behind the gutting of the Voting Rights Act, the implementation of illegal voter ID and citizenship requirements. They train “poll watchers.” These individuals funded Breitbart and produced anti-Democratic media and campaigns. They invented the War on Cops and actively work to dismantle civil rights and pass anti-immigrant and anti-POC legislation. The most prominent members in their network are currently occupying the white house and enacting the agenda contracted between them and Vladimir Putin.</p>
<p>Putin also had to identify his opposition and their strengths and weaknesses in countering the maneuvers of the GOP. That honor would go to the Democratic Party — and its defensively inadequate core. The Democrats have stood by and done absolutely nothing as communities of color stood helpless against police brutality and the inaction of Congress, the Department of Justice and the Attorney General. They did nothing as the Crosscheck voter purge system was implemented across the country and the Voting Rights Act was gutted. They did nothing to protect Tribal sovereignty at Standing Rock. They refused to take action to provide a living wage and fair housing to their working-class constituents and refused to enforce compliance with ADA standards even on election day. They even refused to legally counter Citizens United v FEC or Shelby County v Holder.</p>',
 '3/20/2017', 'true', 'politics, celebrities, future', 4578, 1376, 7894, 10, 1);
INSERT INTO articles
(author_id, title, body, date_published, published, tags, views, likes, bookmarks, responses, response_parent)
VALUES
(2, 1, 'Killing Us Softly', '<P>Dave Chappelle’s two comeback stand-up specials for Netflix find the legendary comedian mining a rich vein of gallows humor. Sometimes you laugh, sometimes you cry, sometimes you wince — but he always makes you think.</P>
 <p>Ten minutes into The Age of Spin, the first of two new Dave Chappelle Netflix specials streaming now (the other is Deep in the Heart of Texas), the veteran comedian settles into a personal account of the dreaded Routine Traffic Stop. It ends with him getting to drive off gingerly at 30 miles an hour on the highway — Breathalyzers don’t pick up weed, he explains — but rarely does it go so smoothly for black people not named Dave Chappelle. He goes on to talk about Marlene Pinnock, who in 2014 was beaten by a California highway patrolman on the side of a freeway, in full view of rush-hour traffic, which was, to put it simply, fucked up. Chappelle:</p>
 <blockquote>“… It was so fucked up that it didn’t even go to court. The city of L.A. just gave this woman one and a half million dollars for her pain and suffering. That is not bad, considering that’s the same amount of money Marcos Maidana got to fight Floyd Mayweather the second time. And this woman obviously hasn’t trained a day in her life. You could see it on the tape — her guards were low, she was taking a lot of shots.”</bockquote>
 <p>The morbid joke is hilarious because honestly, who thinks like that? (The answer is plenty of people; it’s just that they’re usually looking at grainy dash cam footage talking about how, if it had been them, they would’ve complied.) It’s also hilarious because of how Chappelle squawks his fight analysis with glee, which is at odds with the frankly macabre content of the joke itself.</p>
 <p>Strip the antics, lay the facts bare, and it’s sobering, as most real things are. To be nonwhite in America is often to feel targeted and walled in. It’s difficult to explain that feeling without sounding defeatist or suicidal. The joke works because you need the laugh, more than you could’ve possibly imagined. And it’s important because of the conversations it could spark. What would we do without jokes? Despair <i>full time</i>, probably.</p>
 <p>If comedy truly is tragedy plus time, then gallows humor — laughing when there’s nothing to laugh about and there’s nothing immediately better to do — tends to alchemize tragedy. Because time is ever growing short. Dave Chappelle knows the social heft of this mission; it drove him to Africa and cost him $50 million. As the story goes, he was struck on set during a racially charged skit (that’s almost all of them) by an uncomfortably jolly laugh from a white spectator. Chappelle couldn’t abide being misunderstood about topics that carry this much weight. So he went home.</p>
<p>And now he’s back.</p><p>Two years ago, Scottish folk singer-producer Ian McCalman gathered songs, poems, and letters from World War I into a compilation called Far Far From Ypres, and he noticed a recurring theme. While under the ever-present threat of being blown to smithereens by mortar shells, young and largely doomed men clung to fatalism and dark comedy like a life raft. Not knowing when death was coming or in what form it would arrive, soldiers had a lot of time to think about why they were being sent in scores to face it. In the absence of any real answers, they made light of it instead: “We’re here because we’re here because we’re here,” one of the songs went. It was funny, but in a blithe and detached way, buoying up just high enough above catastrophe to be able to appreciate the drollery of it.</p>
 <p>There are earlier and more exact examples of gallows humor. There’s a particularly good one where a condemned criminal in Edo, Japan, jokes about swallowing stones to damage an executioner’s blade, and more than a few that involve actual gallows, obviously. But among my favorite examples is Patrice O’Neal’s idea of the “high-level white woman.” (It’s not especially important to note, but you should know that I can’t read the name “Natalee Holloway” anymore without mentally singing it with O’Neal’s teasing lilt.)</p>
 <p>The late comic, who you may recognize as Pitbull from the “Playa Haters’ Ball,” had a gift for scraping away affectation and wielding unease — particularly, but not exclusively, white guilt — like a blunt instrument. At the beginning of his final special, 2011’s Elephant in the Room, O’Neal singles out a black man and his white girlfriend in the audience, and congratulates the dude on landing a “high-level white woman.” How to know she’s “high level”? How long would the authorities look for her, were she to go missing?</p>
 <p>(This is meant to make you examine why you’re laughing at the idea of a “high-level white woman” at all.)</p>
 <p>There’s nothing funny about the disappearance of Natalee Holloway. There’s also nothing funny about Joran van der Sloot, or his second and non-blonde-haired-blue-eyed victim, Stephany Flores Ramirez. (I had to Google this, too, by the way; none of us are as righteous or innocent as we imagine ourselves to be, and there’s humor in that too.)</p>
 <p>What is funny is the image of O’Neal going out on the water with a white baby on a keychain. It’s a tradition in black comedy to imagine life with the figurative invincibility that white people have — the feeling that lets you end a high-speed car chase with a one-woman dance party soundtracked by Future and police sirens. On the surface, these jokes are about the absurdity of that double standard. But they’re also about why the double standard exists in the first place, and who benefits from it. Whose demonstration gets to shut down traffic without anyone being honked at or detained? Who gets to mourn what they’ve lost and who’s told to get over it? What makes pain ordinary, and what makes it worth acknowledging? Moreover, how am I supposed to give a fuck about animals when there are <i>actual, human people</i> being tossed into the exhaust trails of the backburner?</p>
 <p>During that 2011 special, O’Neal satirizes a PETA commercial, and addresses the crowd while stroking an imaginary one-eyed kitten: “Hi. I’m White Lady, and I’m here to tell you that … niggas probably did it.” When he hosted Saturday Night Live last November, Chappelle recalled how Cincinnati police had said the shooting of Harambe — the rampantly eulogized gorilla that was killed to save a child who fell into his zoo enclosure — was the hardest decision the department had ever had to make: “You’re about to see a lot of niggas in gorilla suits,” he reasoned. The jokes write themselves.</p>',
 '4/1/2017', 'true', 'celebrities, humor, art', 432, 657, 89, 241, 2);


INSERT INTO articles
(author_id, title, body, date_published, published, tags, views, likes, bookmarks, responses, response_parent)
VALUES
(3, 2, '10 Interview Questions Every JavaScript Developer Should Know',
 '<p>At most companies, management must trust the developers to give technical interviews in order to assess candidate skills. If you do well as a candidate, you’ll eventually need to interview. Here’s how.</p>
<h2>You Might Not Agree, and That’s OK</h2>
<p>I advise people to hire based on whether or not a developer believes in class inheritance. Why? Because people who love it are obstinately stubborn about it. They will go to their graves clutching to it. As Bruce Lee famously said:</p>
 <blockquote>“Those who are unaware they are walking in darkness will never seek the light.”</blockquote>
<p>I won’t hire them. You shouldn’t, either.</p>
<p>I’ve seen classes wreak havoc on projects, companies, and lives. Many brilliant people disagree with my views. However, before dismissing my opinion out of hand, consider these points:</p>
<p><b>I ran an app consulting firm</b> in the early days of SaaS, starting before the term was coined. I have worked on hundreds of projects for both startups and fortune 500 companies. I have a background in C++/Java (and assembly, AutoLisp, Delphi, etc…), and I consulted on dozens of Java and C++ apps (both class-oriented OOP languages). I was once an avid supporter of classical inheritance, and even wrote multi-language Rapid Application Development (RAD) tools for it.</p>
<p>I saw up close the many ways in which the class paradigm invited unwary developers down the wrong road, and I saw the extremely costly effects. I’ve seen products abruptly discontinued to stop losses, programmers laid off, and companies brought to their knees by brittle, tangled codebases caused primarily by the improper use of classes and class inheritance.</p>
<p>Class in JS is not harmless sugar for prototypal OO. Class is a virus that infects everything it touches. It came to us formally in JavaScript with ES6, and at the same time, React was taking off. Lots of people started using classes for React components (you don’t have to: the new React 0.14 supports pure function components, or try react-stamp).</p>
<p>Many are unaware that you can build React components in a class-free style. This has caused confusion and incompatibility between React components and other composable elements in the React ecosystem (components, mixins, and component wrappers).</p>
<p>During the days of Backbone dominance (Backbone used its own flavor of classes), I watched a once malleable codebase transform into a brittle mess. I saw code complicated by abstractions necessary to unify the calling API of classes that require `new`, and factories that don’t, forcing the use of dependency injection container that ended up coupling every dependent module tightly to the container API. Those of you with Angular experience will understand what I’m talking about. Angular has four different ways to create services, and features a dependency injection container to abstract them all.</p>
<p>Many brilliant people warned of the perils of class inheritance decades ago, before JavaScript was invented. You can find their warnings in essays with titles like “Object Oriented Programming Considered Harmful”, “Class Considered Harmful”, and “New Considered Harmful”. Such warnings have been published on Usenet, in academic papers, and respected publications such as Doctor Dobb’s Journal: a magazine that gave us nearly 40 years of software development wisdom before its sunset at the end of 2014. Incidentally, there’s also an essay called “Considered Harmful Considered Harmful”, but I digress.</p>
<p>Joe Armstrong, the creator of Erlang summed up one of the famous problems with class in what has become known as The Gorilla Banana Problem from the great book, “Coders at Work” (buy it, there’s lots of other great stuff in it):</p>
 <blockquote>“The problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. <b>You wanted a banana but what you got was a gorilla holding the banana</b> and the entire jungle.”</blockquote>
 <p>The seminal tome of OO design, “Design Patterns: Elements of Reusable Object-Oriented Software” — the book from which design patterns get their name — implores:</p>
 <blockquote>“Favor object composition
<br>over class inheritance.”</blockquote>',
 '2/23/2017', 'true', 'JavaScript, tech, React, Angular', 24831, 7658, 435, 76589, 3);
 

INSERT into USERS
(date_joined, email, bio, firstname, lastname, tags)
VALUES
(2013-08-26 12:39:39.122218+02, 'jeremygray001@gmail.com', 'Teacher, Lover of Words, Web Developer', 
'Jeremy', 'Gray', 'JavaScript, CSS, environment, health')